### PR TITLE
update README

### PR DESCRIPTION
**Pull request by rubycop**

### CODE REVIEW

**Comment by rubycop** [comment]
@race-of-sloth

**Comment by rubycop** [comment]
@race-of-sloths

**Comment by race-of-sloths** [comment]
### 🔄 The PR has been merged.
>[!IMPORTANT]
This pull request is a part of the Race of Sloths and has not been scored yet. Scoring will close in 24 hours! 🕰️

**Comment by akorchyn** [comment]
@race-of-sloths score 8

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 8!
You have received 0 Sloth points for this contribution


Congratulations @rubycop! Your PR was highly scored and you completed another monthly streak! To keep your monthly streak make another pull request next month and get 8+ score for it

**Pull request merged**
